site_name: FYAÂ·å¿ƒæ„¿æ‰€å¾€
site_url: https://121rh.com/
site_author: FYA
site_keywords: Javaå¼€å‘ã€Redisç¼“å­˜
site_description: >-
  ä¸“æ³¨äºJavaç¨‹åºå¼€å‘ã€Redisç¼“å­˜ã€SpringCloudã€SpringCloud Alibaba...ä¸ªäººåšå®¢è®°å½•ï¼
copyright: Copyright &copy; 2022-2023  FYAÂ·å¿ƒæ„¿æ‰€å¾€ <a href="https://beian.miit.gov.cn/#/Integrated/index" target="_blank" rel="noopener">é»‘ICPå¤‡17009103å·</a>
# æºç åœ°å€
repo_url: https://github.com/msgrams/msgrams.github.io
repo_name: msgrams
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  # logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  language: zh
  # ç½‘ç«™å­—ä½“
  icon:
    repo: fontawesome/brands/github
    tags:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange # ä½¿ç”¨rootè‡ªå®šä¹‰ # ç®—äº†deep orangeè¿˜æŒºå¥½çœ‹çš„
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.prune
    # - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

plugins:
  - search:
      lang:
        - en
        - zh
        - ja
      separator: '[\s\-\.]+'
      # separator: '[\s\u200b\-]'
  - autolinks #è‡ªåŠ¨é“¾æ¥æ’ä»¶
  - tags:
      tags_file: tags.md #å‘ˆç°æ ‡ç­¾æŒ‡æ•°
      index_page: tags.md #â€œç´¢å¼•â€é¡µé¢
      insert: top #æ˜¾ç¤ºæ–‡ç« çš„æ ‡ç­¾ top or bottom
  - blogging:
      dirs: # è¦åŒ…å«çš„ç›®å½•
        - app
        - pc
      features:
        timeline: {}
        insert: top
      theme:
        name: card #æ‚¬åœæ•ˆæœçš„å¡ç‰‡
        options: # æ·»åŠ â€œç»§ç»­é˜…è¯»â€æŒ‰é’®ã€‚
          # `true` å¦‚æœæŒ‰é’®æ˜¾ç¤ºä¸ºçº¯æ–‡æœ¬
          # `false` å¦‚æœæ˜¾ç¤ºä¸ºçŸ©å½¢æŒ‰é’®ï¼Œåˆ™ä¸å­˜åœ¨
          plain_button: true
          # æ›¿æ¢â€œç»§ç»­é˜…è¯»â€
          label: Read

  - git-revision-date-localized: #æ˜¾ç¤ºé¡µé¢æœ€åä¸€æ¬¡ git ä¿®æ”¹çš„æ—¥æœŸ
      type: datetime
      timezone: Asia/Shanghai
      enable_creation_date: true
      exclude:
        - comments.md
  - rss:
      abstract_chars_count: 160 # -1 for full content
      categories:
        - timeline
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  social:
    - icon: fontawesome/solid/rss
      link: https://121rh.com/feed_rss_updated.xml
      name: RSSè®¢é˜…
    - icon: fontawesome/solid/paper-plane
      link: mailto:<msgrams@163.com>
      name: å‘é€163é‚®ä»¶
    - icon: fontawesome/brands/qq
      link: tencent://message/?Menu=yes&uin=1434090053&Service=300&sigT=45a1e5847943b64c6ff3990f8a9e644d2b31356cb0b4ac6b24663a3c8dd0f8aa12a595b1714f9d45
      name: QQè”ç³»æˆ‘å“Ÿ
    # - icon: fontawesome/brands/github
    #   link: https://gitee.com/fya666
    #   name: Giteeåœ°å€
    # - icon: fontawesome/brands/weibo
    #   link: https://weibo.com/fyawbz
    #   name: å¾®åšè”ç³»æˆ‘å“Ÿ
    # - icon: fontawesome/brands/weixin
    #   link: /life/weixin/
    #   name: å¾®ä¿¡è”ç³»æˆ‘å“Ÿ
  #vssue: FYA
  #generator: false

extra_css:
  - https://qiniu.121rh.com/css/extra.css
  - https://qiniu.121rh.com/css/video-js.min.css
  - https://qiniu.121rh.com/css/video.css
  - https://qiniu.121rh.com/css/vssue.css
  - https://qiniu.121rh.com/css/vssue.min.css

extra_javascript:
  - https://js.121rh.com/js/extra.js
  - https://js.121rh.com/js/video.min.js
  - https://js.121rh.com/js/vue.js
  - https://js.121rh.com/js/time.js
  #- https://js.121rh.com/js/mouse.js
  - https://js.121rh.com/js/console.js
  #- https://js.121rh.com/js/fireworks.js
  - https://js.121rh.com/js/anime.min.js
  - https://js.121rh.com/js/jquery-3.3.1.min.js
  - https://js.121rh.com/js/G-CHY1TBZZVW.js
  - https://js.121rh.com/js/G-NRCPMZGDT9.js
  - http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: msgrams
      repo: msgrams
  - pymdownx.smartsymbols
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - meta
  - def_list
  - toc:
      permalink: ğŸª # âš“ï¸ #ğŸŸ  # æ˜¾ç¤ºé”šç‚¹
      slugify: !!python/name:pymdownx.slugs.uslugify # æ˜¾ç¤ºä¸€äº›Unicodeçš„æ ‡è¯†ç¬¦


  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - ä¸»é¡µ: index.md
  - ç”Ÿæ´»: life/index.md
  - æ—¶é—´çº¿: timeline.md
  - æ‰“æ ‡ç­¾: tags.md
  - ç®—æ³•: algs/index.md
