site_name: FYAÂ·å¿ƒæ„¿æ‰€å¾€
site_url: https://121rh.com/
site_author: FYA
site_keywords: Javaå¼€å‘ã€Redisç¼“å­˜
site_description: >-
  ä¸“æ³¨äºJavaç¨‹åºå¼€å‘ã€Redisç¼“å­˜ã€SpringCloudã€SpringCloud Alibaba...ä¸ªäººåšå®¢è®°å½•ï¼
copyright: Copyright Â©ï¸ 2022-2024 FYAÂ·å¿ƒæ„¿æ‰€å¾€  <a href="https://beian.miit.gov.cn/#/Integrated/recordQuery" target="_blank" rel="noopener">é»‘ICPå¤‡17009103å·</a>
repo_url: https://github.com/msgrams/msgrams.github.io
repo_name: msgrams
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.png
  language: zh
  icon:
    repo: fontawesome/brands/github
    tags:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange # ä½¿ç”¨rootè‡ªå®šä¹‰ # ç®—äº†deep orangeè¿˜æŒºå¥½çœ‹çš„
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - search:
      lang:
        - en
        - zh
        - ja
      separator: '[\s\-\.]+'
  - autolinks #è‡ªåŠ¨é“¾æ¥æ’ä»¶
  - tags:
      tags_file: tags.md #å‘ˆç°æ ‡ç­¾æŒ‡æ•°
      index_page: tags.md #â€œç´¢å¼•â€é¡µé¢
      insert: top #æ˜¾ç¤ºæ–‡ç« çš„æ ‡ç­¾ top or bottom
  - blogging:
      dirs: # è¦åŒ…å«çš„ç›®å½•
        - app
        - pc
      features:
        timeline: {}
        insert: top
      theme:
        name: card #æ‚¬åœæ•ˆæœçš„å¡ç‰‡
        options: # æ·»åŠ â€œç»§ç»­é˜…è¯»â€æŒ‰é’®ã€‚
          # `true` å¦‚æœæŒ‰é’®æ˜¾ç¤ºä¸ºçº¯æ–‡æœ¬
          # `false` å¦‚æœæ˜¾ç¤ºä¸ºçŸ©å½¢æŒ‰é’®ï¼Œåˆ™ä¸å­˜åœ¨
          plain_button: true
          # æ›¿æ¢â€œç»§ç»­é˜…è¯»â€
          label: Read

  - git-revision-date-localized: #æ˜¾ç¤ºé¡µé¢æœ€åä¸€æ¬¡ git ä¿®æ”¹çš„æ—¥æœŸ
      type: datetime
      timezone: Asia/Shanghai
      enable_creation_date: true
      exclude:
        - comments.md
  - rss:
      abstract_chars_count: 160 # -1 for full content
      categories:
        - timeline
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
      enabled: true
      feed_ttl: 1440
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      length: 20
      pretty_print: false
      match_path: ".*"
      url_parameters:
        utm_source: "documentation"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"

extra:
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  social:
    - icon: fontawesome/solid/rss
      link: https://121rh.com/feed_rss_updated.xml
      name: RSSè®¢é˜…
    - icon: fontawesome/solid/paper-plane
      link: mailto:<lizhi@121rh.com>
      name: é‚®ä»¶åœ°å€
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Wish0580
      name: Twitterè”ç³»æˆ‘å“Ÿ!
    - icon: fontawesome/brands/telegram
      link: https://t.me/Amqess
      name: Telegramè”ç³»å“Ÿ!
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/fyagrams/
      name: Instagramç§å¯†å·

extra_css:
  - https://qiniu.121rh.com/css/extra.css
  - https://qiniu.121rh.com/css/video-js.min.css
  - https://qiniu.121rh.com/css/video.css
  - https://qiniu.121rh.com/css/vssue.css
  - https://qiniu.121rh.com/css/vssue.min.css

extra_javascript:
  - https://js.121rh.com/js/extra.js
  - https://js.121rh.com/js/video.min.js
  - https://js.121rh.com/js/vue.js
  - https://js.121rh.com/js/time.js
  - https://js.121rh.com/js/console.js
  - https://js.121rh.com/js/anime.min.js
  - https://js.121rh.com/js/jquery-3.3.1.min.js
  - https://js.121rh.com/js/G-CHY1TBZZVW.js
  - https://js.121rh.com/js/G-NRCPMZGDT9.js
  - http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  #- https://js.121rh.com/js/mouse.js
  #- https://js.121rh.com/js/fireworks.js
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: msgrams
      repo: msgrams
  - pymdownx.smartsymbols
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - meta
  - def_list
  - toc:
      permalink: ğŸª # âš“ï¸ #ğŸŸ  # æ˜¾ç¤ºé”šç‚¹
      slugify: !!python/name:pymdownx.slugs.uslugify # æ˜¾ç¤ºä¸€äº›Unicodeçš„æ ‡è¯†ç¬¦


  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - ä¸»é¡µ: index.md
  - å…³äºæˆ‘: life/index.md
  - æ—¶é—´çº¿: timeline.md
  - æ‰“æ ‡ç­¾: tags.md
  - ç®—æ³•: algs/index.md
